name: Deploy

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: development
        type: environment

permissions: 
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure to Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              -f infra/main.bicep \
              -g ${{ secrets.AZURE_RG_NAME }} \
              -p discordBotPublicKey="${{ secrets.DISCORD_BOT_PUBLIC_KEY }}" \
              -p discordBotToken="${{ secrets.DISCORD_BOT_TOKEN }}" \
              ${{ vars.AZ_DEPLOYMENT_INLINE_PARAMS }}
