name: Deploy

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: development
        type: environment
      whatif_only:
        description: 'Only run What If'
        required: false
        default: false
        type: boolean
      additional_params:
        description: 'Additional parameters to pass to the deployment'
        required: false
        default: ''
        type: string

permissions: 
  id-token: write

env:
  AZ_INLINE_SCRIPT_PARAMS: |
    -f infra/main.bicep \
    -g ${{ secrets.AZURE_RG_NAME }} \
    -p discordBotPublicKey="${{ secrets.DISCORD_BOT_PUBLIC_KEY }}" \
    -p discordBotToken="${{ secrets.DISCORD_BOT_TOKEN }}" \
    -p dockerHubUsername"${{ secrets.DOCKER_HUB_USER }}" \
    -p dockerHubPassword"${{ secrets.DOCKER_HUB_PAT }}" \
    ${{ vars.AZ_DEPLOYMENT_INLINE_PARAMS }} \
    ${{ github.event.inputs.additional_params }} > whatif
  DEPLOYMENT_NAME: ${{ github.run_id }}


jobs:
  what_if:
    runs-on: ubuntu-latest
    name: What If
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: What If
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group what-if \
              ${{ env.AZ_INLINE_SCRIPT_PARAMS }}

      # Create string output of Whatif
      - name: Create Job Summary
        id: whatif-string
        run: |
          WHATIF=$(cat whatif)
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## ARM What If Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```log' >> $GITHUB_OUTPUT
          echo "$WHATIF" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # Publish Terraform Plan as task summary
      - name: Publish Job Summary
        env:
          SUMMARY: ${{ steps.whatif-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    needs: what_if
    environment: ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.whatif_only == 'false' }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure to Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create -n ${{ env.DEPLOYMENT_NAME }} \
              ${{ env.AZ_INLINE_SCRIPT_PARAMS }}
