name: Azure Minecraft

on:
  workflow_dispatch:

jobs:
  build_iac:
    name: Build Infrastructure as Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Bicep File
        run: az bicep build --file infra/main.bicep

  build_discord-bot:
    name: Build and Push Discord Bot
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/discord-bot
    steps:
      - uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          file: ./src/discord-bot/Azmc.DiscordBot/Dockerfile
          context: ./src/discord-bot/Azmc.DiscordBot
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_map-renderer:
    name: Build and Push Map Renderer
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/map-renderer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          file: ./src/map-renderer/Dockerfile
          context: ./src/map-renderer
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
