name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_iac:
    name: Build Infrastructure as Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Bicep File
        run: az bicep build --file infra/main.bicep

  build_discord-bot:
    name: Build Discord Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./src/discord-bot/Azmc.DiscordBot/Dockerfile
          context: ./src/discord-bot
