name: Tag Docker Images on Release

on:
  release:
    types:
      - created

jobs:
  tag_images:
    name: Tag Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - name: discord-bot
            dockerfile: ./src/discord-bot/Azmc.DiscordBot/Dockerfile
            context: ./src/discord-bot
          - name: map-renderer
            dockerfile: ./src/map-renderer/Dockerfile
            context: ./src/map-renderer
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/${{ matrix.image.name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          file: ${{ matrix.image.dockerfile }}
          context: ${{ matrix.image.context }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
